[functions]
directory = "netlify/functions"

[build]
  command = "echo 'No build step'"
  publish = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
